### ISSUE TITLE
setup script not installing the pogs library itself

### ISSUE THREAD

**Issue by socathie** [bungun/optkit#2]
Thanks for directing me from pogs-python to here.

Using `python setup.py install` in `optkit\python`, and in python, using the command, `import optkit` I get the following error. Looking through the directories, seems like these library files were not installed anywhere and hence cannot be accessed.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/pymvpa/lib/python2.7/site-packages/optkit/__init__.py", line 4, in <module>
    from optkit.api import OPTKIT_VERSION
  File "/home/ubuntu/anaconda3/envs/pymvpa/lib/python2.7/site-packages/optkit/api.py", line 13, in <module>
    backend = OKBackend()
  File "/home/ubuntu/anaconda3/envs/pymvpa/lib/python2.7/site-packages/optkit/backends.py", line 28, in __init__
    self.pogs_lib_loader = PogsLibs()
  File "/home/ubuntu/anaconda3/envs/pymvpa/lib/python2.7/site-packages/optkit/libs/pogs.py", line 19, in __init__
    OptkitLibs.__init__(self, 'libpogs_dense_')
  File "/home/ubuntu/anaconda3/envs/pymvpa/lib/python2.7/site-packages/optkit/libs/loader.py", line 40, in __init__
    search_results))
ValueError: No backend libraries were located:

library libpogs_dense_gpu32.so not found at /home/ubuntu/anaconda3/envs/pymvpa/lib/python2.7/build/libpogs_dense_gpu32.so.
library libpogs_dense_gpu64.so not found at /home/ubuntu/anaconda3/envs/pymvpa/lib/python2.7/build/libpogs_dense_gpu64.so.
library libpogs_dense_cpu32.so not found at /home/ubuntu/anaconda3/envs/pymvpa/lib/python2.7/build/libpogs_dense_cpu32.so.
library libpogs_dense_cpu64.so not found at /home/ubuntu/anaconda3/envs/pymvpa/lib/python2.7/build/libpogs_dense_cpu64.so.
```

**Comment by bungun** [comment]
Could you share the log output from the setup script? 
That should record whether the C libraries were built and where they were copied to.

**Comment by fishdda** [comment]
Hi, I seems to have the same error here.
![image](https://user-images.githubusercontent.com/23411165/115986640-c834e100-a5e3-11eb-8828-a90102b183ff.png)

and the setup script output is attached here:
![image](https://user-images.githubusercontent.com/23411165/115986674-ee5a8100-a5e3-11eb-8c0d-04f1862f581f.png)

**Comment by ttruneh** [comment]
Hi, I'm also getting the same errors when running - python setup.py install in optkit\python, and in python, using the command, import optkit  - did anyone find a solution to the above problem?
Thanks!

**Comment by ttruneh** [comment]
Actually, ignore my post - installing using the dev branch works fine for me!
